export const dropInConfigs = [
  { theme: 'ambiance', mode: 'javascript' },
  { theme: 'chaos', mode: 'javascript' },
  { theme: 'chrome', mode: 'javascript' },
  // { theme: 'clouds', mode: 'javascript' },
  // { theme: 'clouds_midnight', mode: 'javascript' },
  // { theme: 'cobalt', mode: 'javascript' },
  // { theme: 'crimson_editor', mode: 'javascript' },
  // { theme: 'dawn', mode: 'javascript' },
  // { theme: 'dreamweaver', mode: 'javascript' },
  // { theme: 'eclipse', mode: 'javascript' },
  // { theme: 'github', mode: 'javascript' },
  // { theme: 'idle_fingers', mode: 'javascript' },
  // { theme: 'katzenmilch', mode: 'javascript' },
  // { theme: 'kr_theme', mode: 'javascript' },
  // { theme: 'kuroir', mode: 'javascript' },
  // { theme: 'merbivore', mode: 'javascript' },
  // { theme: 'merbivore_soft', mode: 'javascript' },
  // { theme: 'mono_industrial', mode: 'javascript' },
  // { theme: 'monokai', mode: 'javascript' },
  // { theme: 'pastel_on_dark', mode: 'javascript' },
  // { theme: 'solarized_dark', mode: 'javascript' },
  // { theme: 'solarized_light', mode: 'javascript' },
  // { theme: 'terminal', mode: 'javascript' },
  // { theme: 'textmate', mode: 'javascript' },
  // { theme: 'tomorrow', mode: 'javascript' },
  // { theme: 'tomorrow_night', mode: 'javascript' },
  // { theme: 'tomorrow_night_blue', mode: 'javascript' },
  // { theme: 'tomorrow_night_bright', mode: 'javascript' },
  // { theme: 'tomorrow_night_eighties', mode: 'javascript' },
  // { theme: 'twilight', mode: 'javascript' },
  // { theme: 'vibrant_ink', mode: 'javascript' },
  // { theme: 'xcode', mode: 'javascript' },
];
